### ISSUE TITLE
Add User Interface for Mining Native phonons

### ISSUE THREAD

**Issue by douglance** [GridPlus/phonon-app#21]

**Comment by maevyn11** [comment]
This can now be done in conjunction with https://github.com/GridPlus/phonon-client/issues/191. 

Could be a separate screen or simply a button on the home screen, but either way it should be clear in the UI that the rest of the card's functions are unavailable while mining is taking place.

**Comment by italianst4** [comment]
@zerodouglas I'm not seeing mined phonons when call `/listPhonons` after successful mining.  Thoughts?

**Comment by italianst4** [comment]
This was completed with merging PR #49 . Closing.
