### ISSUE TITLE
Display Card Name Instead of CardID at Startup when Available

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-app#32]
Testing this out, the name appears to be getting set on card correctly, but if I restart the app it goes back to displaying the CardID rather than the name in the frontend. Can we display the Name instead of the cardId on the lock screen and main page if it's available?

_Originally posted by @maevyn11 in https://github.com/GridPlus/phonon-app/issues/31#issuecomment-1191935968_

**Comment by douglance** [comment]
I can't replicate that behavior locally.  
  
Are you sure you're testing the latest on the branch? It should be a09fbb0

**Comment by maevyn11** [comment]
Yes, testing with latest client `friendly-name` branch 6fe66de88ad8163621d54e417eb7954408a69cad with latest `dl/friendly` a09fbb05c61f200eec45cb2fe33d42aa46cd09d9

Surprised, as it seems to reproduce every time for me. Here's my process, let me know if you still can't reproduce it. 

To reproduce 
1. Set the Name through clicking the name in the center of the app. 
2. Close the app down 
3. Start it up again. 

CardID appears on the lock screen instead of name
4.Unlock the card
CardID appears on center of the screen instead CardID.

**Comment by douglance** [comment]
Are you sure the name is being saved?

**Comment by maevyn11** [comment]
I did rebuild, trying it again now to confirm. 

By closing the app I mean killing the server process. In my case I am running the frontend through the embedding in the server, so this shuts down both at once.

**Comment by maevyn11** [comment]
So it looks like the name is set on the card, but when the app is restarted the frontend's call to listSessions is returning "" instead of the actual name.

**Comment by maevyn11** [comment]
Created this issue in `phonon-client` to track the necessary changes on that side, hopefully that's enough to resolve the issue. 

https://github.com/GridPlus/phonon-client/issues/178

**Comment by maevyn11** [comment]
Confirmed that this works now that https://github.com/GridPlus/phonon-client/issues/178 has been handled.
