### ISSUE TITLE
Error handling for redeeming phonons

### ISSUE THREAD

**Issue by italianst4** [GridPlus/phonon-app#48]
The UI doesn't tell the user when redeeming phonons fails.  

Reproducible steps:
1. Mine a phonon
2. Send to a testnet ETH address
3. You should get the following error: `ECC pubkey format could not be detected`

**Comment by douglance** [comment]
btw, you can add `Closes #{issue number}` when putting in a PR to automatically close issues when a PR merges. It helps manage issues.

**Comment by italianst4** [comment]
will do, appreciate the tip.
