### ISSUE TITLE
Wrong Chain Displayed in Send Modal

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-app#50]
Issue: Wrong Chain displayed when sending an asset. 
Steps to recreate: When sending an asset the confirmation screen appears to always say Ropsten instead of the actual chain of the asset.
Means to resolve: None at the moment.
OS: Windows 11 and OSX 10.14.6
Browser: Brave 1.42.95 (edited)
![image](https://user-images.githubusercontent.com/6888231/186704424-eed11f03-f15d-43ab-ab9a-08b39e16e920.png)

**Comment by italianst4** [comment]
This was resolved with merging PR #49 . Closing.
