### ISSUE TITLE
Unclear which Phonon Denomination are Valid

### ISSUE THREAD

**Issue by maevyn11** [GridPlus/phonon-app#52]
Issue:  "Invalid Denomination" error received when creating a phonon with 3+ decimals (e.g., .325 Rinkeby ETH), 4+ digits (e.g., 3025), and sometimes 3 digits (e.g., 999). Occasionally, an amount of .125 is accepted, while .525 throws the error. Close window, try to create a new phonon of .525 and it is accepted.
Steps to recreate: Create a backed phonon of .### asset. Change amount and error messages is intermittent. Close 'Create' window, reopen, enter same amount and test. Or, create a phonon of thousands will throw error also.
Means to resolve: Restarting the client sometimes fixes it, but errors reappear. Especially when changing amount numerous time in the same modal screen. 
OS:  MacOS Monterey 12.4
Browser:  Chrome Version 103.0.5060.114

Some explanation should be given to the user on the Create modal to specify what valid values are. Ultimately, we should expand this datatype so it's not restricted to so few significant digits.

**Comment by italianst4** [comment]
@maevyn11 or @zerodouglas I took a look at this a bit further and the `/checkDenomination` endpoint is returning an error with values such as:
- 0.325
- 0.3025
- 0.525

Note: To improve the UI, I can display the error message from the endpoint, in this case, it's returning: "cannot make phonon denomination from value: value cannot be represented as a phonon denomination\n". 

Thoughts?

**Comment by maevyn11** [comment]
I don't think the help text from that error is helpful enough to the user because it doesn't tell them why the value is invalid or what they need to do do fix the issue. Think we should include some text like: 
"Phonon Denominations must have significant digits <255" 

Idk if the concept of significant digits is clear enough though, maybe some examples. Ultimately we should probably lift this requirement and improve the card implementation to handle more granular values.
