### ISSUE TITLE
Add ui element to indicate if the telemetry key is working

### ISSUE THREAD

**Issue by npmaile** [GridPlus/phonon-app#55]
it's not documented otherwise, but the endpoint is `/telemetryCheck`
it will return `200` with no body if the telemetry key is working
will return `500` with `telemetry check not successful` in the body if it isn't working 

it's already on the master branch of phonon-ciient

probably poll the endpoint once every 30 seconds

**Comment by italianst4** [comment]
@npmaile, I added a subtle indicator in the bottom right of the UI.

Example:
![Screen Shot 2022-09-01 at 19 45 08](https://user-images.githubusercontent.com/215719/188030860-a9f566bb-f8ad-4b2a-9f71-e01fa5f08a5b.png)

I'm not sure if there's something I need to do to get the telemetry response to 200.  I've only seen it return "not connected". 

Thoughts on the UI element position/size/visual and returning a 200?

**Comment by npmaile** [comment]
that is precisely what I'm looking for. 
is your telemetry key configured properly? it should come back with 200 if it is

**Comment by italianst4** [comment]
how does one do that?
