### ISSUE TITLE
Sessions page crashes after creating a phonon

### ISSUE THREAD

**Issue by ahinchliff** [GridPlus/phonon-app#7]
After creating a phonon the app crashes with the error
`PhononListItem.tsx:16 Uncaught TypeError: Cannot read properties of undefined (reading 'icon')`. 

It appears the type `Phonon` is not accurate. In `src/types/index.ts` the type is declared as
```
export type Phonon = {
  index: number;
  pubKey: string;
  type: number;
  value: number;
};
```

While the shape of the `phonon` prop being passed into the `PhononListItem` component is 
```
{
    "KeyIndex": 0,
    "PubKey": "045825e490967c7dcd3de095902a692942014be4c57e6ca9284d06fc74c5f8d9a37d5d564c64128a5b9a414a65055adf14f8a912629c8563d35e35479ade388dd3",
    "CurrencyType": 1
}
```

**Comment by douglance** [comment]
@ahinchliff Could you share some details about your environment that might help me debug?

**Comment by ahinchliff** [comment]
@douglance, I've realised that my `phonon-client` project was a commit behind. I am unable to verify checking out "latest" fixes my issue because in the browser console I am seeing `VM569:1 GET http://localhost:3000/listSessions 404 (Not Found)`. Please see my steps below and tell me where I am going wrong. 

Phonon app - caf68b500dfac7e6a4bf5b249daff6733c8799d7
Phonon client - f7c0a80d3faf30a73feee1350bacdb4bceee9684

1. In `phonon-client` project,  run `go run main/phonon.go webUI`.
2. In second terminal, from `phonon-app`, run `npm i && npm run start`
3. From browser, visit `http://localhost:8080/genMock`
4. From browser, visit `http://localhost:3000` and see `VM569:1 GET http://localhost:3000/listSessions 404 (Not Found)` in console. 

After step 3, I am able to see `installed cert:....` in the `phonon-client` logs so I suspect a mock card is being correctly created. 

Thanks

**Comment by douglance** [comment]
@ahinchliff Could you please edit the `baseUrl` in `src/store/api.ts` to be this: 

```
const baseUrl = isPlatform("capacitor")
  ? "https://localhost:8080/"
  : "/";
  ```

and add `"proxy": "http://localhost:8080",` to line 5 in the `package.json`. 

Please let me know if that fixes the issue for you.

**Comment by ahinchliff** [comment]
@douglance, unfortunately no luck. 

When I've checked out master branch for both phonon-app and phonon-client I have the same issue regardless of if I apply your suggested changes. 

If i checkout master branch for phonon-app and commit `0932f46f8b3bee95d92feb89cae2b7287f150ede` for phonon-client I am to see a list of my sessions in the web app but I am faced with the original issue. 

Can you confirm you are seeing no issues when running both repos from master branch?
